name = "canvas-app-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "canvas-app-jwt-secret-change-in-production"
ALLOWED_ORIGINS = "https://canvas-app-1gz.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "canvas-app-db"
database_id = "2327a3cb-925e-4873-98c0-ef241093a8d1"
